version: '3'
services:
  php:
    build:
      args:
        user: docker
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    expose:  
      - 9000  
    volumes:
      - ./app:/app
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
  mysql:
    image: mariadb:latest
    restart: always
    ports:
        - "3306:3306"
    environment:
      MARIADB_DATABASE: "db"
      MARIADB_ROOT_PASSWORD: "555@@@"
      MARIADB_PASSWORD: "444@@@"
      MARIADB_USER: "mysql_jean-paul"
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
